version: "3.9"
services:

  redis:
    extends:
      file: compose.yml
      service: redis

  controller:
    extends:
      file: compose.yml
      service: controller

  test_full:
    image: drpilman/test_full
    build:
      context: test/full
    network_mode: "host"
    depends_on:
      controller:
        condition: service_healthy
