version: "3.9"
services:
  redis:
    image: redis:7.0.0-alpine3.15
    ports:
      - "8001:8001"
      - "6379:6379"
  controller:
    image: drpilman/controller
    build:
      context: controller
    ports:
      - "8000:8000"
    environment:
      - DETECTOR_IMAGE=drpilman/testdetector
      - DEVICE=cpu
      - REDIS_HOST=redis
    volumes:
      - ./store:/app/store
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - redis
  web:
    image: drpilman/web
    build:
      context: web
      args:
        API_HOST: 127.0.0.1:8000
    ports:
      - "3000:3000"
    depends_on:
      - controller
