version: "3.9"
services:

  redis:
    extends:
      file: test.yml
      service: redis

  controller:
    extends:
      file: test.yml
      service: controller

  pytest:
    image: drpilman/testapi
    build:
      context: controller/tests
    network_mode: "host"
    depends_on:
      controller:
        condition: service_healthy
